// Données mock pour le développement local (sans Supabase)
import type { User, ProProfile, AppelOffre, Offre, Conversation, Message } from '@/types'

export const MOCK_USERS: User[] = [
  {
    id: 'client-1',
    email: 'mairie.lyon@test.fr',
    role: 'client',
    prenom: 'Sophie',
    nom: 'Martin',
    commune: 'Lyon',
    telephone: '0478000001',
    created_at: '2024-01-10T10:00:00Z',
  },
  {
    id: 'client-2',
    email: 'syndic.paris@test.fr',
    role: 'client',
    prenom: 'Jean',
    nom: 'Dupont',
    commune: 'Paris',
    telephone: '0144000002',
    created_at: '2024-01-12T10:00:00Z',
  },
  {
    id: 'pro-1',
    email: 'arbre.expert@test.fr',
    role: 'pro',
    prenom: 'Marc',
    nom: 'Leblanc',
    commune: 'Villeurbanne',
    telephone: '0478000010',
    created_at: '2024-01-05T10:00:00Z',
  },
  {
    id: 'pro-2',
    email: 'verdure.paysage@test.fr',
    role: 'pro',
    prenom: 'Lucie',
    nom: 'Bernard',
    commune: 'Bron',
    telephone: '0478000011',
    created_at: '2024-01-07T10:00:00Z',
  },
  {
    id: 'pro-3',
    email: 'entretien.parc@test.fr',
    role: 'pro',
    prenom: 'Thomas',
    nom: 'Petit',
    commune: 'Décines',
    telephone: '0478000012',
    created_at: '2024-01-08T10:00:00Z',
  },
  {
    id: 'admin-1',
    email: 'admin@verticall.fr',
    role: 'admin',
    prenom: 'Admin',
    nom: 'VertiCall',
    created_at: '2024-01-01T10:00:00Z',
  },
]

export const MOCK_PRO_PROFILES: ProProfile[] = [
  {
    id: 'pp-1',
    user_id: 'pro-1',
    raison_sociale: 'Arbre Expert SARL',
    siret: '12345678900001',
    metier: 'elagueur',
    departements: ['69', '01', '38'],
    description: 'Spécialiste de l\'élagage et abattage depuis 15 ans. Certifié arboriste.',
    note_moyenne: 4.8,
    nb_contrats: 47,
    verifie: true,
    created_at: '2024-01-05T10:00:00Z',
  },
  {
    id: 'pp-2',
    user_id: 'pro-2',
    raison_sociale: 'Verdure & Paysage',
    siret: '98765432100002',
    metier: 'paysagiste',
    departements: ['69', '42'],
    description: 'Création et aménagement d\'espaces verts. Référence en espaces publics.',
    note_moyenne: 4.5,
    nb_contrats: 31,
    verifie: true,
    created_at: '2024-01-07T10:00:00Z',
  },
  {
    id: 'pp-3',
    user_id: 'pro-3',
    raison_sociale: 'Entretien Parcs & Jardins',
    siret: '55544433300003',
    metier: 'entretien',
    departements: ['69'],
    description: 'Entretien régulier espaces verts collectifs, tonte, désherbage.',
    note_moyenne: 4.2,
    nb_contrats: 18,
    verifie: false,
    created_at: '2024-01-08T10:00:00Z',
  },
]

export const MOCK_AOS: AppelOffre[] = [
  {
    id: 'ao-1',
    client_id: 'client-1',
    client_nom: 'Mairie de Lyon',
    client_commune: 'Lyon',
    titre: 'Élagage parc de la Tête d\'Or — Printemps 2024',
    description: 'Élagage de 45 arbres dans le parc municipal. Essences variées (platanes, chênes, érables). Travail en hauteur nécessaire.',
    categorie: 'elagage',
    departement: '69',
    budget_min: 8000,
    budget_max: 15000,
    date_souhaitee: '2024-04-15',
    statut: 'publie',
    nb_offres: 2,
    created_at: '2024-02-01T10:00:00Z',
  },
  {
    id: 'ao-2',
    client_id: 'client-1',
    client_nom: 'Mairie de Lyon',
    client_commune: 'Lyon',
    titre: 'Entretien espaces verts — Résidence Les Acacias',
    description: 'Contrat annuel d\'entretien : tonte, taille haies, désherbage allées. 3 passages par mois.',
    categorie: 'entretien',
    departement: '69',
    budget_min: 3000,
    budget_max: 5000,
    date_souhaitee: '2024-03-01',
    statut: 'en_cours',
    nb_offres: 3,
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 'ao-3',
    client_id: 'client-2',
    client_nom: 'Syndic Île-de-France',
    client_commune: 'Paris',
    titre: 'Création jardin partagé — Copropriété Voltaire',
    description: 'Aménagement d\'un jardin partagé sur 200m². Pergola, potager, zone de compostage, végétalisation clôture.',
    categorie: 'creation',
    departement: '75',
    budget_min: 12000,
    budget_max: 20000,
    date_souhaitee: '2024-05-30',
    statut: 'publie',
    nb_offres: 1,
    created_at: '2024-02-10T10:00:00Z',
  },
  {
    id: 'ao-4',
    client_id: 'client-1',
    client_nom: 'Mairie de Lyon',
    client_commune: 'Lyon',
    titre: 'Abattage sécurisé peupliers — Zone inondable',
    description: 'Abattage de 8 peupliers en zone inondable. Contraintes d\'accès importantes, travail avec nacelle.',
    categorie: 'elagage',
    departement: '69',
    budget_min: 5000,
    budget_max: 9000,
    date_souhaitee: '2024-03-20',
    statut: 'termine',
    nb_offres: 2,
    created_at: '2024-01-15T10:00:00Z',
  },
]

export const MOCK_OFFRES: Offre[] = [
  {
    id: 'offre-1',
    ao_id: 'ao-1',
    pro_id: 'pro-1',
    pro_nom: 'Arbre Expert SARL',
    pro_metier: 'Élagueur certifié',
    pro_note: 4.8,
    montant: 11500,
    delai: '2024-04-10',
    description: 'Intervention avec nacelle 25m. Équipe de 3 personnes. Évacuation déchets incluse.',
    statut: 'soumise',
    created_at: '2024-02-05T10:00:00Z',
  },
  {
    id: 'offre-2',
    ao_id: 'ao-1',
    pro_id: 'pro-2',
    pro_nom: 'Verdure & Paysage',
    pro_metier: 'Paysagiste',
    pro_note: 4.5,
    montant: 13200,
    delai: '2024-04-20',
    description: 'Élagage soigné avec taille de formation. Rapport arboricole fourni.',
    statut: 'soumise',
    created_at: '2024-02-07T10:00:00Z',
  },
  {
    id: 'offre-3',
    ao_id: 'ao-2',
    pro_id: 'pro-3',
    pro_nom: 'Entretien Parcs & Jardins',
    pro_metier: 'Entretien espaces verts',
    pro_note: 4.2,
    montant: 3800,
    delai: '2024-03-01',
    description: 'Contrat annuel. Intervention chaque semaine. Devis mensuel.',
    statut: 'selectionnee',
    created_at: '2024-01-25T10:00:00Z',
  },
  {
    id: 'offre-4',
    ao_id: 'ao-3',
    pro_id: 'pro-2',
    pro_nom: 'Verdure & Paysage',
    pro_metier: 'Paysagiste',
    pro_note: 4.5,
    montant: 16800,
    delai: '2024-05-20',
    description: 'Projet complet clé en main. Plans fournis avant démarrage.',
    statut: 'soumise',
    created_at: '2024-02-15T10:00:00Z',
  },
]

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv-1',
    ao_id: 'ao-1',
    ao_titre: 'Élagage parc de la Tête d\'Or',
    client_id: 'client-1',
    client_nom: 'Mairie de Lyon',
    pro_id: 'pro-1',
    pro_nom: 'Arbre Expert SARL',
    dernier_message: 'Pouvez-vous préciser le type de nacelle disponible ?',
    dernier_message_at: '2024-02-06T14:30:00Z',
    nb_non_lus: 1,
  },
  {
    id: 'conv-2',
    ao_id: 'ao-2',
    ao_titre: 'Entretien Résidence Les Acacias',
    client_id: 'client-1',
    client_nom: 'Mairie de Lyon',
    pro_id: 'pro-3',
    pro_nom: 'Entretien Parcs & Jardins',
    dernier_message: 'Parfait, on démarre le 1er mars.',
    dernier_message_at: '2024-01-28T09:00:00Z',
    nb_non_lus: 0,
  },
]

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    conversation_id: 'conv-1',
    expediteur_id: 'client-1',
    expediteur_nom: 'Mairie de Lyon',
    expediteur_role: 'client',
    contenu: 'Bonjour, votre offre est intéressante. Avez-vous déjà travaillé dans ce parc ?',
    lu: true,
    created_at: '2024-02-05T16:00:00Z',
  },
  {
    id: 'msg-2',
    conversation_id: 'conv-1',
    expediteur_id: 'pro-1',
    expediteur_nom: 'Arbre Expert SARL',
    expediteur_role: 'pro',
    contenu: 'Oui, nous sommes intervenus en 2022 pour les platanes de l\'allée principale.',
    lu: true,
    created_at: '2024-02-05T17:20:00Z',
  },
  {
    id: 'msg-3',
    conversation_id: 'conv-1',
    expediteur_id: 'client-1',
    expediteur_nom: 'Mairie de Lyon',
    expediteur_role: 'client',
    contenu: 'Pouvez-vous préciser le type de nacelle disponible ?',
    lu: false,
    created_at: '2024-02-06T14:30:00Z',
  },
  {
    id: 'msg-4',
    conversation_id: 'conv-2',
    expediteur_id: 'client-1',
    expediteur_nom: 'Mairie de Lyon',
    expediteur_role: 'client',
    contenu: 'Votre offre a été retenue. Merci de confirmer votre disponibilité.',
    lu: true,
    created_at: '2024-01-27T10:00:00Z',
  },
  {
    id: 'msg-5',
    conversation_id: 'conv-2',
    expediteur_id: 'pro-3',
    expediteur_nom: 'Entretien Parcs & Jardins',
    expediteur_role: 'pro',
    contenu: 'Parfait, on démarre le 1er mars.',
    lu: true,
    created_at: '2024-01-28T09:00:00Z',
  },
]
